spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: user
    url: jdbc:postgresql://db-payment:5432/db
    username: user
  cloud:
    openfeign:
      lazy-attributes-resolution: true

server:
  port: 8082

app:
  config:
    webhook-url: /v1/ticket/status-webhook