spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: user
    url: jdbc:postgresql://db-ticket:5432/db
    username: user
  kafka:
    bootstrap-servers: kafka1:19092
  data:
    rest:
      detection-strategy: annotated
      base-path: v1
    jpa:
      show-sql: true

server:
  port: 8081

app:
  config:
    page-size: 10
    kafka:
      booking-status-topic: booking-status
    ftp:
      server: ftp-server
      username: user
      password: 123
